<?php
declare(strict_types=1);

namespace Pentagonal\Sso\Core\Database\Schema\Attributes;

use function str_replace;
use function strtolower;

class Collations
{
    public const UCA1400_AI_CI = 'uca1400_ai_ci';
    public const UCA1400_AI_CS = 'uca1400_ai_cs';
    public const UCA1400_AS_CI = 'uca1400_as_ci';
    public const UCA1400_AS_CS = 'uca1400_as_cs';
    public const UCA1400_NOPAD_AI_CI = 'uca1400_nopad_ai_ci';
    public const UCA1400_NOPAD_AI_CS = 'uca1400_nopad_ai_cs';
    public const UCA1400_NOPAD_AS_CI = 'uca1400_nopad_as_ci';
    public const UCA1400_NOPAD_AS_CS = 'uca1400_nopad_as_cs';
    public const UCA1400_ICELANDIC_AI_CI = 'uca1400_icelandic_ai_ci';
    public const UCA1400_ICELANDIC_AI_CS = 'uca1400_icelandic_ai_cs';
    public const UCA1400_ICELANDIC_AS_CI = 'uca1400_icelandic_as_ci';
    public const UCA1400_ICELANDIC_AS_CS = 'uca1400_icelandic_as_cs';
    public const UCA1400_ICELANDIC_NOPAD_AI_CI = 'uca1400_icelandic_nopad_ai_ci';
    public const UCA1400_ICELANDIC_NOPAD_AI_CS = 'uca1400_icelandic_nopad_ai_cs';
    public const UCA1400_ICELANDIC_NOPAD_AS_CI = 'uca1400_icelandic_nopad_as_ci';
    public const UCA1400_ICELANDIC_NOPAD_AS_CS = 'uca1400_icelandic_nopad_as_cs';
    public const UCA1400_LATVIAN_AI_CI = 'uca1400_latvian_ai_ci';
    public const UCA1400_LATVIAN_AI_CS = 'uca1400_latvian_ai_cs';
    public const UCA1400_LATVIAN_AS_CI = 'uca1400_latvian_as_ci';
    public const UCA1400_LATVIAN_AS_CS = 'uca1400_latvian_as_cs';
    public const UCA1400_LATVIAN_NOPAD_AI_CI = 'uca1400_latvian_nopad_ai_ci';
    public const UCA1400_LATVIAN_NOPAD_AI_CS = 'uca1400_latvian_nopad_ai_cs';
    public const UCA1400_LATVIAN_NOPAD_AS_CI = 'uca1400_latvian_nopad_as_ci';
    public const UCA1400_LATVIAN_NOPAD_AS_CS = 'uca1400_latvian_nopad_as_cs';
    public const UCA1400_ROMANIAN_AI_CI = 'uca1400_romanian_ai_ci';
    public const UCA1400_ROMANIAN_AI_CS = 'uca1400_romanian_ai_cs';
    public const UCA1400_ROMANIAN_AS_CI = 'uca1400_romanian_as_ci';
    public const UCA1400_ROMANIAN_AS_CS = 'uca1400_romanian_as_cs';
    public const UCA1400_ROMANIAN_NOPAD_AI_CI = 'uca1400_romanian_nopad_ai_ci';
    public const UCA1400_ROMANIAN_NOPAD_AI_CS = 'uca1400_romanian_nopad_ai_cs';
    public const UCA1400_ROMANIAN_NOPAD_AS_CI = 'uca1400_romanian_nopad_as_ci';
    public const UCA1400_ROMANIAN_NOPAD_AS_CS = 'uca1400_romanian_nopad_as_cs';
    public const UCA1400_SLOVENIAN_AI_CI = 'uca1400_slovenian_ai_ci';
    public const UCA1400_SLOVENIAN_AI_CS = 'uca1400_slovenian_ai_cs';
    public const UCA1400_SLOVENIAN_AS_CI = 'uca1400_slovenian_as_ci';
    public const UCA1400_SLOVENIAN_AS_CS = 'uca1400_slovenian_as_cs';
    public const UCA1400_SLOVENIAN_NOPAD_AI_CI = 'uca1400_slovenian_nopad_ai_ci';
    public const UCA1400_SLOVENIAN_NOPAD_AI_CS = 'uca1400_slovenian_nopad_ai_cs';
    public const UCA1400_SLOVENIAN_NOPAD_AS_CI = 'uca1400_slovenian_nopad_as_ci';
    public const UCA1400_SLOVENIAN_NOPAD_AS_CS = 'uca1400_slovenian_nopad_as_cs';
    public const UCA1400_POLISH_AI_CI = 'uca1400_polish_ai_ci';
    public const UCA1400_POLISH_AI_CS = 'uca1400_polish_ai_cs';
    public const UCA1400_POLISH_AS_CI = 'uca1400_polish_as_ci';
    public const UCA1400_POLISH_AS_CS = 'uca1400_polish_as_cs';
    public const UCA1400_POLISH_NOPAD_AI_CI = 'uca1400_polish_nopad_ai_ci';
    public const UCA1400_POLISH_NOPAD_AI_CS = 'uca1400_polish_nopad_ai_cs';
    public const UCA1400_POLISH_NOPAD_AS_CI = 'uca1400_polish_nopad_as_ci';
    public const UCA1400_POLISH_NOPAD_AS_CS = 'uca1400_polish_nopad_as_cs';
    public const UCA1400_ESTONIAN_AI_CI = 'uca1400_estonian_ai_ci';
    public const UCA1400_ESTONIAN_AI_CS = 'uca1400_estonian_ai_cs';
    public const UCA1400_ESTONIAN_AS_CI = 'uca1400_estonian_as_ci';
    public const UCA1400_ESTONIAN_AS_CS = 'uca1400_estonian_as_cs';
    public const UCA1400_ESTONIAN_NOPAD_AI_CI = 'uca1400_estonian_nopad_ai_ci';
    public const UCA1400_ESTONIAN_NOPAD_AI_CS = 'uca1400_estonian_nopad_ai_cs';
    public const UCA1400_ESTONIAN_NOPAD_AS_CI = 'uca1400_estonian_nopad_as_ci';
    public const UCA1400_ESTONIAN_NOPAD_AS_CS = 'uca1400_estonian_nopad_as_cs';
    public const UCA1400_SPANISH_AI_CI = 'uca1400_spanish_ai_ci';
    public const UCA1400_SPANISH_AI_CS = 'uca1400_spanish_ai_cs';
    public const UCA1400_SPANISH_AS_CI = 'uca1400_spanish_as_ci';
    public const UCA1400_SPANISH_AS_CS = 'uca1400_spanish_as_cs';
    public const UCA1400_SPANISH_NOPAD_AI_CI = 'uca1400_spanish_nopad_ai_ci';
    public const UCA1400_SPANISH_NOPAD_AI_CS = 'uca1400_spanish_nopad_ai_cs';
    public const UCA1400_SPANISH_NOPAD_AS_CI = 'uca1400_spanish_nopad_as_ci';
    public const UCA1400_SPANISH_NOPAD_AS_CS = 'uca1400_spanish_nopad_as_cs';
    public const UCA1400_SWEDISH_AI_CI = 'uca1400_swedish_ai_ci';
    public const UCA1400_SWEDISH_AI_CS = 'uca1400_swedish_ai_cs';
    public const UCA1400_SWEDISH_AS_CI = 'uca1400_swedish_as_ci';
    public const UCA1400_SWEDISH_AS_CS = 'uca1400_swedish_as_cs';
    public const UCA1400_SWEDISH_NOPAD_AI_CI = 'uca1400_swedish_nopad_ai_ci';
    public const UCA1400_SWEDISH_NOPAD_AI_CS = 'uca1400_swedish_nopad_ai_cs';
    public const UCA1400_SWEDISH_NOPAD_AS_CI = 'uca1400_swedish_nopad_as_ci';
    public const UCA1400_SWEDISH_NOPAD_AS_CS = 'uca1400_swedish_nopad_as_cs';
    public const UCA1400_TURKISH_AI_CI = 'uca1400_turkish_ai_ci';
    public const UCA1400_TURKISH_AI_CS = 'uca1400_turkish_ai_cs';
    public const UCA1400_TURKISH_AS_CI = 'uca1400_turkish_as_ci';
    public const UCA1400_TURKISH_AS_CS = 'uca1400_turkish_as_cs';
    public const UCA1400_TURKISH_NOPAD_AI_CI = 'uca1400_turkish_nopad_ai_ci';
    public const UCA1400_TURKISH_NOPAD_AI_CS = 'uca1400_turkish_nopad_ai_cs';
    public const UCA1400_TURKISH_NOPAD_AS_CI = 'uca1400_turkish_nopad_as_ci';
    public const UCA1400_TURKISH_NOPAD_AS_CS = 'uca1400_turkish_nopad_as_cs';
    public const UCA1400_CZECH_AI_CI = 'uca1400_czech_ai_ci';
    public const UCA1400_CZECH_AI_CS = 'uca1400_czech_ai_cs';
    public const UCA1400_CZECH_AS_CI = 'uca1400_czech_as_ci';
    public const UCA1400_CZECH_AS_CS = 'uca1400_czech_as_cs';
    public const UCA1400_CZECH_NOPAD_AI_CI = 'uca1400_czech_nopad_ai_ci';
    public const UCA1400_CZECH_NOPAD_AI_CS = 'uca1400_czech_nopad_ai_cs';
    public const UCA1400_CZECH_NOPAD_AS_CI = 'uca1400_czech_nopad_as_ci';
    public const UCA1400_CZECH_NOPAD_AS_CS = 'uca1400_czech_nopad_as_cs';
    public const UCA1400_DANISH_AI_CI = 'uca1400_danish_ai_ci';
    public const UCA1400_DANISH_AI_CS = 'uca1400_danish_ai_cs';
    public const UCA1400_DANISH_AS_CI = 'uca1400_danish_as_ci';
    public const UCA1400_DANISH_AS_CS = 'uca1400_danish_as_cs';
    public const UCA1400_DANISH_NOPAD_AI_CI = 'uca1400_danish_nopad_ai_ci';
    public const UCA1400_DANISH_NOPAD_AI_CS = 'uca1400_danish_nopad_ai_cs';
    public const UCA1400_DANISH_NOPAD_AS_CI = 'uca1400_danish_nopad_as_ci';
    public const UCA1400_DANISH_NOPAD_AS_CS = 'uca1400_danish_nopad_as_cs';
    public const UCA1400_LITHUANIAN_AI_CI = 'uca1400_lithuanian_ai_ci';
    public const UCA1400_LITHUANIAN_AI_CS = 'uca1400_lithuanian_ai_cs';
    public const UCA1400_LITHUANIAN_AS_CI = 'uca1400_lithuanian_as_ci';
    public const UCA1400_LITHUANIAN_AS_CS = 'uca1400_lithuanian_as_cs';
    public const UCA1400_LITHUANIAN_NOPAD_AI_CI = 'uca1400_lithuanian_nopad_ai_ci';
    public const UCA1400_LITHUANIAN_NOPAD_AI_CS = 'uca1400_lithuanian_nopad_ai_cs';
    public const UCA1400_LITHUANIAN_NOPAD_AS_CI = 'uca1400_lithuanian_nopad_as_ci';
    public const UCA1400_LITHUANIAN_NOPAD_AS_CS = 'uca1400_lithuanian_nopad_as_cs';
    public const UCA1400_SLOVAK_AI_CI = 'uca1400_slovak_ai_ci';
    public const UCA1400_SLOVAK_AI_CS = 'uca1400_slovak_ai_cs';
    public const UCA1400_SLOVAK_AS_CI = 'uca1400_slovak_as_ci';
    public const UCA1400_SLOVAK_AS_CS = 'uca1400_slovak_as_cs';
    public const UCA1400_SLOVAK_NOPAD_AI_CI = 'uca1400_slovak_nopad_ai_ci';
    public const UCA1400_SLOVAK_NOPAD_AI_CS = 'uca1400_slovak_nopad_ai_cs';
    public const UCA1400_SLOVAK_NOPAD_AS_CI = 'uca1400_slovak_nopad_as_ci';
    public const UCA1400_SLOVAK_NOPAD_AS_CS = 'uca1400_slovak_nopad_as_cs';
    public const UCA1400_SPANISH2_AI_CI = 'uca1400_spanish2_ai_ci';
    public const UCA1400_SPANISH2_AI_CS = 'uca1400_spanish2_ai_cs';
    public const UCA1400_SPANISH2_AS_CI = 'uca1400_spanish2_as_ci';
    public const UCA1400_SPANISH2_AS_CS = 'uca1400_spanish2_as_cs';
    public const UCA1400_SPANISH2_NOPAD_AI_CI = 'uca1400_spanish2_nopad_ai_ci';
    public const UCA1400_SPANISH2_NOPAD_AI_CS = 'uca1400_spanish2_nopad_ai_cs';
    public const UCA1400_SPANISH2_NOPAD_AS_CI = 'uca1400_spanish2_nopad_as_ci';
    public const UCA1400_SPANISH2_NOPAD_AS_CS = 'uca1400_spanish2_nopad_as_cs';
    public const UCA1400_ROMAN_AI_CI = 'uca1400_roman_ai_ci';
    public const UCA1400_ROMAN_AI_CS = 'uca1400_roman_ai_cs';
    public const UCA1400_ROMAN_AS_CI = 'uca1400_roman_as_ci';
    public const UCA1400_ROMAN_AS_CS = 'uca1400_roman_as_cs';
    public const UCA1400_ROMAN_NOPAD_AI_CI = 'uca1400_roman_nopad_ai_ci';
    public const UCA1400_ROMAN_NOPAD_AI_CS = 'uca1400_roman_nopad_ai_cs';
    public const UCA1400_ROMAN_NOPAD_AS_CI = 'uca1400_roman_nopad_as_ci';
    public const UCA1400_ROMAN_NOPAD_AS_CS = 'uca1400_roman_nopad_as_cs';
    public const UCA1400_PERSIAN_AI_CI = 'uca1400_persian_ai_ci';
    public const UCA1400_PERSIAN_AI_CS = 'uca1400_persian_ai_cs';
    public const UCA1400_PERSIAN_AS_CI = 'uca1400_persian_as_ci';
    public const UCA1400_PERSIAN_AS_CS = 'uca1400_persian_as_cs';
    public const UCA1400_PERSIAN_NOPAD_AI_CI = 'uca1400_persian_nopad_ai_ci';
    public const UCA1400_PERSIAN_NOPAD_AI_CS = 'uca1400_persian_nopad_ai_cs';
    public const UCA1400_PERSIAN_NOPAD_AS_CI = 'uca1400_persian_nopad_as_ci';
    public const UCA1400_PERSIAN_NOPAD_AS_CS = 'uca1400_persian_nopad_as_cs';
    public const UCA1400_ESPERANTO_AI_CI = 'uca1400_esperanto_ai_ci';
    public const UCA1400_ESPERANTO_AI_CS = 'uca1400_esperanto_ai_cs';
    public const UCA1400_ESPERANTO_AS_CI = 'uca1400_esperanto_as_ci';
    public const UCA1400_ESPERANTO_AS_CS = 'uca1400_esperanto_as_cs';
    public const UCA1400_ESPERANTO_NOPAD_AI_CI = 'uca1400_esperanto_nopad_ai_ci';
    public const UCA1400_ESPERANTO_NOPAD_AI_CS = 'uca1400_esperanto_nopad_ai_cs';
    public const UCA1400_ESPERANTO_NOPAD_AS_CI = 'uca1400_esperanto_nopad_as_ci';
    public const UCA1400_ESPERANTO_NOPAD_AS_CS = 'uca1400_esperanto_nopad_as_cs';
    public const UCA1400_HUNGARIAN_AI_CI = 'uca1400_hungarian_ai_ci';
    public const UCA1400_HUNGARIAN_AI_CS = 'uca1400_hungarian_ai_cs';
    public const UCA1400_HUNGARIAN_AS_CI = 'uca1400_hungarian_as_ci';
    public const UCA1400_HUNGARIAN_AS_CS = 'uca1400_hungarian_as_cs';
    public const UCA1400_HUNGARIAN_NOPAD_AI_CI = 'uca1400_hungarian_nopad_ai_ci';
    public const UCA1400_HUNGARIAN_NOPAD_AI_CS = 'uca1400_hungarian_nopad_ai_cs';
    public const UCA1400_HUNGARIAN_NOPAD_AS_CI = 'uca1400_hungarian_nopad_as_ci';
    public const UCA1400_HUNGARIAN_NOPAD_AS_CS = 'uca1400_hungarian_nopad_as_cs';
    public const UCA1400_SINHALA_AI_CI = 'uca1400_sinhala_ai_ci';
    public const UCA1400_SINHALA_AI_CS = 'uca1400_sinhala_ai_cs';
    public const UCA1400_SINHALA_AS_CI = 'uca1400_sinhala_as_ci';
    public const UCA1400_SINHALA_AS_CS = 'uca1400_sinhala_as_cs';
    public const UCA1400_SINHALA_NOPAD_AI_CI = 'uca1400_sinhala_nopad_ai_ci';
    public const UCA1400_SINHALA_NOPAD_AI_CS = 'uca1400_sinhala_nopad_ai_cs';
    public const UCA1400_SINHALA_NOPAD_AS_CI = 'uca1400_sinhala_nopad_as_ci';
    public const UCA1400_SINHALA_NOPAD_AS_CS = 'uca1400_sinhala_nopad_as_cs';
    public const UCA1400_GERMAN2_AI_CI = 'uca1400_german2_ai_ci';
    public const UCA1400_GERMAN2_AI_CS = 'uca1400_german2_ai_cs';
    public const UCA1400_GERMAN2_AS_CI = 'uca1400_german2_as_ci';
    public const UCA1400_GERMAN2_AS_CS = 'uca1400_german2_as_cs';
    public const UCA1400_GERMAN2_NOPAD_AI_CI = 'uca1400_german2_nopad_ai_ci';
    public const UCA1400_GERMAN2_NOPAD_AI_CS = 'uca1400_german2_nopad_ai_cs';
    public const UCA1400_GERMAN2_NOPAD_AS_CI = 'uca1400_german2_nopad_as_ci';
    public const UCA1400_GERMAN2_NOPAD_AS_CS = 'uca1400_german2_nopad_as_cs';
    public const UCA1400_VIETNAMESE_AI_CI = 'uca1400_vietnamese_ai_ci';
    public const UCA1400_VIETNAMESE_AI_CS = 'uca1400_vietnamese_ai_cs';
    public const UCA1400_VIETNAMESE_AS_CI = 'uca1400_vietnamese_as_ci';
    public const UCA1400_VIETNAMESE_AS_CS = 'uca1400_vietnamese_as_cs';
    public const UCA1400_VIETNAMESE_NOPAD_AI_CI = 'uca1400_vietnamese_nopad_ai_ci';
    public const UCA1400_VIETNAMESE_NOPAD_AI_CS = 'uca1400_vietnamese_nopad_ai_cs';
    public const UCA1400_VIETNAMESE_NOPAD_AS_CI = 'uca1400_vietnamese_nopad_as_ci';
    public const UCA1400_VIETNAMESE_NOPAD_AS_CS = 'uca1400_vietnamese_nopad_as_cs';
    public const UCA1400_CROATIAN_AI_CI = 'uca1400_croatian_ai_ci';
    public const UCA1400_CROATIAN_AI_CS = 'uca1400_croatian_ai_cs';
    public const UCA1400_CROATIAN_AS_CI = 'uca1400_croatian_as_ci';
    public const UCA1400_CROATIAN_AS_CS = 'uca1400_croatian_as_cs';
    public const UCA1400_CROATIAN_NOPAD_AI_CI = 'uca1400_croatian_nopad_ai_ci';
    public const UCA1400_CROATIAN_NOPAD_AI_CS = 'uca1400_croatian_nopad_ai_cs';
    public const UCA1400_CROATIAN_NOPAD_AS_CI = 'uca1400_croatian_nopad_as_ci';
    public const UCA1400_CROATIAN_NOPAD_AS_CS = 'uca1400_croatian_nopad_as_cs';
    public const BIG5_CHINESE_CI = 'big5_chinese_ci';
    public const LATIN2_CZECH_CS = 'latin2_czech_cs';
    public const DEC8_SWEDISH_CI = 'dec8_swedish_ci';
    public const CP850_GENERAL_CI = 'cp850_general_ci';
    public const LATIN1_GERMAN1_CI = 'latin1_german1_ci';
    public const HP8_ENGLISH_CI = 'hp8_english_ci';
    public const KOI8R_GENERAL_CI = 'koi8r_general_ci';
    public const LATIN1_SWEDISH_CI = 'latin1_swedish_ci';
    public const LATIN2_GENERAL_CI = 'latin2_general_ci';
    public const SWE7_SWEDISH_CI = 'swe7_swedish_ci';
    public const ASCII_GENERAL_CI = 'ascii_general_ci';
    public const UJIS_JAPANESE_CI = 'ujis_japanese_ci';
    public const SJIS_JAPANESE_CI = 'sjis_japanese_ci';
    public const CP1251_BULGARIAN_CI = 'cp1251_bulgarian_ci';
    public const LATIN1_DANISH_CI = 'latin1_danish_ci';
    public const HEBREW_GENERAL_CI = 'hebrew_general_ci';
    public const TIS620_THAI_CI = 'tis620_thai_ci';
    public const EUCKR_KOREAN_CI = 'euckr_korean_ci';
    public const LATIN7_ESTONIAN_CS = 'latin7_estonian_cs';
    public const LATIN2_HUNGARIAN_CI = 'latin2_hungarian_ci';
    public const KOI8U_GENERAL_CI = 'koi8u_general_ci';
    public const CP1251_UKRAINIAN_CI = 'cp1251_ukrainian_ci';
    public const GB2312_CHINESE_CI = 'gb2312_chinese_ci';
    public const GREEK_GENERAL_CI = 'greek_general_ci';
    public const CP1250_GENERAL_CI = 'cp1250_general_ci';
    public const LATIN2_CROATIAN_CI = 'latin2_croatian_ci';
    public const GBK_CHINESE_CI = 'gbk_chinese_ci';
    public const CP1257_LITHUANIAN_CI = 'cp1257_lithuanian_ci';
    public const LATIN5_TURKISH_CI = 'latin5_turkish_ci';
    public const LATIN1_GERMAN2_CI = 'latin1_german2_ci';
    public const ARMSCII8_GENERAL_CI = 'armscii8_general_ci';
    public const UTF8MB3_GENERAL_CI = 'utf8mb3_general_ci';
    public const CP1250_CZECH_CS = 'cp1250_czech_cs';
    public const UCS2_GENERAL_CI = 'ucs2_general_ci';
    public const CP866_GENERAL_CI = 'cp866_general_ci';
    public const KEYBCS2_GENERAL_CI = 'keybcs2_general_ci';
    public const MACCE_GENERAL_CI = 'macce_general_ci';
    public const MACROMAN_GENERAL_CI = 'macroman_general_ci';
    public const CP852_GENERAL_CI = 'cp852_general_ci';
    public const LATIN7_GENERAL_CI = 'latin7_general_ci';
    public const LATIN7_GENERAL_CS = 'latin7_general_cs';
    public const MACCE_BIN = 'macce_bin';
    public const CP1250_CROATIAN_CI = 'cp1250_croatian_ci';
    public const UTF8MB4_GENERAL_CI = 'utf8mb4_general_ci';
    public const UTF8MB4_BIN = 'utf8mb4_bin';
    public const LATIN1_BIN = 'latin1_bin';
    public const LATIN1_GENERAL_CI = 'latin1_general_ci';
    public const LATIN1_GENERAL_CS = 'latin1_general_cs';
    public const CP1251_BIN = 'cp1251_bin';
    public const CP1251_GENERAL_CI = 'cp1251_general_ci';
    public const CP1251_GENERAL_CS = 'cp1251_general_cs';
    public const MACROMAN_BIN = 'macroman_bin';
    public const UTF16_GENERAL_CI = 'utf16_general_ci';
    public const UTF16_BIN = 'utf16_bin';
    public const UTF16LE_GENERAL_CI = 'utf16le_general_ci';
    public const CP1256_GENERAL_CI = 'cp1256_general_ci';
    public const CP1257_BIN = 'cp1257_bin';
    public const CP1257_GENERAL_CI = 'cp1257_general_ci';
    public const UTF32_GENERAL_CI = 'utf32_general_ci';
    public const UTF32_BIN = 'utf32_bin';
    public const UTF16LE_BIN = 'utf16le_bin';
    public const BINARY = 'binary';
    public const ARMSCII8_BIN = 'armscii8_bin';
    public const ASCII_BIN = 'ascii_bin';
    public const CP1250_BIN = 'cp1250_bin';
    public const CP1256_BIN = 'cp1256_bin';
    public const CP866_BIN = 'cp866_bin';
    public const DEC8_BIN = 'dec8_bin';
    public const GREEK_BIN = 'greek_bin';
    public const HEBREW_BIN = 'hebrew_bin';
    public const HP8_BIN = 'hp8_bin';
    public const KEYBCS2_BIN = 'keybcs2_bin';
    public const KOI8R_BIN = 'koi8r_bin';
    public const KOI8U_BIN = 'koi8u_bin';
    public const LATIN2_BIN = 'latin2_bin';
    public const LATIN5_BIN = 'latin5_bin';
    public const LATIN7_BIN = 'latin7_bin';
    public const CP850_BIN = 'cp850_bin';
    public const CP852_BIN = 'cp852_bin';
    public const SWE7_BIN = 'swe7_bin';
    public const UTF8MB3_BIN = 'utf8mb3_bin';
    public const BIG5_BIN = 'big5_bin';
    public const EUCKR_BIN = 'euckr_bin';
    public const GB2312_BIN = 'gb2312_bin';
    public const GBK_BIN = 'gbk_bin';
    public const SJIS_BIN = 'sjis_bin';
    public const TIS620_BIN = 'tis620_bin';
    public const UCS2_BIN = 'ucs2_bin';
    public const UJIS_BIN = 'ujis_bin';
    public const GEOSTD8_GENERAL_CI = 'geostd8_general_ci';
    public const GEOSTD8_BIN = 'geostd8_bin';
    public const LATIN1_SPANISH_CI = 'latin1_spanish_ci';
    public const CP932_JAPANESE_CI = 'cp932_japanese_ci';
    public const CP932_BIN = 'cp932_bin';
    public const EUCJPMS_JAPANESE_CI = 'eucjpms_japanese_ci';
    public const EUCJPMS_BIN = 'eucjpms_bin';
    public const CP1250_POLISH_CI = 'cp1250_polish_ci';
    public const UTF16_UNICODE_CI = 'utf16_unicode_ci';
    public const UTF16_ICELANDIC_CI = 'utf16_icelandic_ci';
    public const UTF16_LATVIAN_CI = 'utf16_latvian_ci';
    public const UTF16_ROMANIAN_CI = 'utf16_romanian_ci';
    public const UTF16_SLOVENIAN_CI = 'utf16_slovenian_ci';
    public const UTF16_POLISH_CI = 'utf16_polish_ci';
    public const UTF16_ESTONIAN_CI = 'utf16_estonian_ci';
    public const UTF16_SPANISH_CI = 'utf16_spanish_ci';
    public const UTF16_SWEDISH_CI = 'utf16_swedish_ci';
    public const UTF16_TURKISH_CI = 'utf16_turkish_ci';
    public const UTF16_CZECH_CI = 'utf16_czech_ci';
    public const UTF16_DANISH_CI = 'utf16_danish_ci';
    public const UTF16_LITHUANIAN_CI = 'utf16_lithuanian_ci';
    public const UTF16_SLOVAK_CI = 'utf16_slovak_ci';
    public const UTF16_SPANISH2_CI = 'utf16_spanish2_ci';
    public const UTF16_ROMAN_CI = 'utf16_roman_ci';
    public const UTF16_PERSIAN_CI = 'utf16_persian_ci';
    public const UTF16_ESPERANTO_CI = 'utf16_esperanto_ci';
    public const UTF16_HUNGARIAN_CI = 'utf16_hungarian_ci';
    public const UTF16_SINHALA_CI = 'utf16_sinhala_ci';
    public const UTF16_GERMAN2_CI = 'utf16_german2_ci';
    public const UTF16_CROATIAN_MYSQL561_CI = 'utf16_croatian_mysql561_ci';
    public const UTF16_UNICODE_520_CI = 'utf16_unicode_520_ci';
    public const UTF16_VIETNAMESE_CI = 'utf16_vietnamese_ci';
    public const UCS2_UNICODE_CI = 'ucs2_unicode_ci';
    public const UCS2_ICELANDIC_CI = 'ucs2_icelandic_ci';
    public const UCS2_LATVIAN_CI = 'ucs2_latvian_ci';
    public const UCS2_ROMANIAN_CI = 'ucs2_romanian_ci';
    public const UCS2_SLOVENIAN_CI = 'ucs2_slovenian_ci';
    public const UCS2_POLISH_CI = 'ucs2_polish_ci';
    public const UCS2_ESTONIAN_CI = 'ucs2_estonian_ci';
    public const UCS2_SPANISH_CI = 'ucs2_spanish_ci';
    public const UCS2_SWEDISH_CI = 'ucs2_swedish_ci';
    public const UCS2_TURKISH_CI = 'ucs2_turkish_ci';
    public const UCS2_CZECH_CI = 'ucs2_czech_ci';
    public const UCS2_DANISH_CI = 'ucs2_danish_ci';
    public const UCS2_LITHUANIAN_CI = 'ucs2_lithuanian_ci';
    public const UCS2_SLOVAK_CI = 'ucs2_slovak_ci';
    public const UCS2_SPANISH2_CI = 'ucs2_spanish2_ci';
    public const UCS2_ROMAN_CI = 'ucs2_roman_ci';
    public const UCS2_PERSIAN_CI = 'ucs2_persian_ci';
    public const UCS2_ESPERANTO_CI = 'ucs2_esperanto_ci';
    public const UCS2_HUNGARIAN_CI = 'ucs2_hungarian_ci';
    public const UCS2_SINHALA_CI = 'ucs2_sinhala_ci';
    public const UCS2_GERMAN2_CI = 'ucs2_german2_ci';
    public const UCS2_CROATIAN_MYSQL561_CI = 'ucs2_croatian_mysql561_ci';
    public const UCS2_UNICODE_520_CI = 'ucs2_unicode_520_ci';
    public const UCS2_VIETNAMESE_CI = 'ucs2_vietnamese_ci';
    public const UCS2_GENERAL_MYSQL500_CI = 'ucs2_general_mysql500_ci';
    public const UTF32_UNICODE_CI = 'utf32_unicode_ci';
    public const UTF32_ICELANDIC_CI = 'utf32_icelandic_ci';
    public const UTF32_LATVIAN_CI = 'utf32_latvian_ci';
    public const UTF32_ROMANIAN_CI = 'utf32_romanian_ci';
    public const UTF32_SLOVENIAN_CI = 'utf32_slovenian_ci';
    public const UTF32_POLISH_CI = 'utf32_polish_ci';
    public const UTF32_ESTONIAN_CI = 'utf32_estonian_ci';
    public const UTF32_SPANISH_CI = 'utf32_spanish_ci';
    public const UTF32_SWEDISH_CI = 'utf32_swedish_ci';
    public const UTF32_TURKISH_CI = 'utf32_turkish_ci';
    public const UTF32_CZECH_CI = 'utf32_czech_ci';
    public const UTF32_DANISH_CI = 'utf32_danish_ci';
    public const UTF32_LITHUANIAN_CI = 'utf32_lithuanian_ci';
    public const UTF32_SLOVAK_CI = 'utf32_slovak_ci';
    public const UTF32_SPANISH2_CI = 'utf32_spanish2_ci';
    public const UTF32_ROMAN_CI = 'utf32_roman_ci';
    public const UTF32_PERSIAN_CI = 'utf32_persian_ci';
    public const UTF32_ESPERANTO_CI = 'utf32_esperanto_ci';
    public const UTF32_HUNGARIAN_CI = 'utf32_hungarian_ci';
    public const UTF32_SINHALA_CI = 'utf32_sinhala_ci';
    public const UTF32_GERMAN2_CI = 'utf32_german2_ci';
    public const UTF32_CROATIAN_MYSQL561_CI = 'utf32_croatian_mysql561_ci';
    public const UTF32_UNICODE_520_CI = 'utf32_unicode_520_ci';
    public const UTF32_VIETNAMESE_CI = 'utf32_vietnamese_ci';
    public const UTF8MB3_UNICODE_CI = 'utf8mb3_unicode_ci';
    public const UTF8MB3_ICELANDIC_CI = 'utf8mb3_icelandic_ci';
    public const UTF8MB3_LATVIAN_CI = 'utf8mb3_latvian_ci';
    public const UTF8MB3_ROMANIAN_CI = 'utf8mb3_romanian_ci';
    public const UTF8MB3_SLOVENIAN_CI = 'utf8mb3_slovenian_ci';
    public const UTF8MB3_POLISH_CI = 'utf8mb3_polish_ci';
    public const UTF8MB3_ESTONIAN_CI = 'utf8mb3_estonian_ci';
    public const UTF8MB3_SPANISH_CI = 'utf8mb3_spanish_ci';
    public const UTF8MB3_SWEDISH_CI = 'utf8mb3_swedish_ci';
    public const UTF8MB3_TURKISH_CI = 'utf8mb3_turkish_ci';
    public const UTF8MB3_CZECH_CI = 'utf8mb3_czech_ci';
    public const UTF8MB3_DANISH_CI = 'utf8mb3_danish_ci';
    public const UTF8MB3_LITHUANIAN_CI = 'utf8mb3_lithuanian_ci';
    public const UTF8MB3_SLOVAK_CI = 'utf8mb3_slovak_ci';
    public const UTF8MB3_SPANISH2_CI = 'utf8mb3_spanish2_ci';
    public const UTF8MB3_ROMAN_CI = 'utf8mb3_roman_ci';
    public const UTF8MB3_PERSIAN_CI = 'utf8mb3_persian_ci';
    public const UTF8MB3_ESPERANTO_CI = 'utf8mb3_esperanto_ci';
    public const UTF8MB3_HUNGARIAN_CI = 'utf8mb3_hungarian_ci';
    public const UTF8MB3_SINHALA_CI = 'utf8mb3_sinhala_ci';
    public const UTF8MB3_GERMAN2_CI = 'utf8mb3_german2_ci';
    public const UTF8MB3_CROATIAN_MYSQL561_CI = 'utf8mb3_croatian_mysql561_ci';
    public const UTF8MB3_UNICODE_520_CI = 'utf8mb3_unicode_520_ci';
    public const UTF8MB3_VIETNAMESE_CI = 'utf8mb3_vietnamese_ci';
    public const UTF8MB3_GENERAL_MYSQL500_CI = 'utf8mb3_general_mysql500_ci';
    public const UTF8MB4_UNICODE_CI = 'utf8mb4_unicode_ci';
    public const UTF8MB4_ICELANDIC_CI = 'utf8mb4_icelandic_ci';
    public const UTF8MB4_LATVIAN_CI = 'utf8mb4_latvian_ci';
    public const UTF8MB4_ROMANIAN_CI = 'utf8mb4_romanian_ci';
    public const UTF8MB4_SLOVENIAN_CI = 'utf8mb4_slovenian_ci';
    public const UTF8MB4_POLISH_CI = 'utf8mb4_polish_ci';
    public const UTF8MB4_ESTONIAN_CI = 'utf8mb4_estonian_ci';
    public const UTF8MB4_SPANISH_CI = 'utf8mb4_spanish_ci';
    public const UTF8MB4_SWEDISH_CI = 'utf8mb4_swedish_ci';
    public const UTF8MB4_TURKISH_CI = 'utf8mb4_turkish_ci';
    public const UTF8MB4_CZECH_CI = 'utf8mb4_czech_ci';
    public const UTF8MB4_DANISH_CI = 'utf8mb4_danish_ci';
    public const UTF8MB4_LITHUANIAN_CI = 'utf8mb4_lithuanian_ci';
    public const UTF8MB4_SLOVAK_CI = 'utf8mb4_slovak_ci';
    public const UTF8MB4_SPANISH2_CI = 'utf8mb4_spanish2_ci';
    public const UTF8MB4_ROMAN_CI = 'utf8mb4_roman_ci';
    public const UTF8MB4_PERSIAN_CI = 'utf8mb4_persian_ci';
    public const UTF8MB4_ESPERANTO_CI = 'utf8mb4_esperanto_ci';
    public const UTF8MB4_HUNGARIAN_CI = 'utf8mb4_hungarian_ci';
    public const UTF8MB4_SINHALA_CI = 'utf8mb4_sinhala_ci';
    public const UTF8MB4_GERMAN2_CI = 'utf8mb4_german2_ci';
    public const UTF8MB4_CROATIAN_MYSQL561_CI = 'utf8mb4_croatian_mysql561_ci';
    public const UTF8MB4_UNICODE_520_CI = 'utf8mb4_unicode_520_ci';
    public const UTF8MB4_VIETNAMESE_CI = 'utf8mb4_vietnamese_ci';
    public const UTF8MB3_CROATIAN_CI = 'utf8mb3_croatian_ci';
    public const UTF8MB3_MYANMAR_CI = 'utf8mb3_myanmar_ci';
    public const UTF8MB3_THAI_520_W2 = 'utf8mb3_thai_520_w2';
    public const UTF8MB4_CROATIAN_CI = 'utf8mb4_croatian_ci';
    public const UTF8MB4_MYANMAR_CI = 'utf8mb4_myanmar_ci';
    public const UTF8MB4_THAI_520_W2 = 'utf8mb4_thai_520_w2';
    public const UCS2_CROATIAN_CI = 'ucs2_croatian_ci';
    public const UCS2_MYANMAR_CI = 'ucs2_myanmar_ci';
    public const UCS2_THAI_520_W2 = 'ucs2_thai_520_w2';
    public const UTF16_CROATIAN_CI = 'utf16_croatian_ci';
    public const UTF16_MYANMAR_CI = 'utf16_myanmar_ci';
    public const UTF16_THAI_520_W2 = 'utf16_thai_520_w2';
    public const UTF32_CROATIAN_CI = 'utf32_croatian_ci';
    public const UTF32_MYANMAR_CI = 'utf32_myanmar_ci';
    public const UTF32_THAI_520_W2 = 'utf32_thai_520_w2';
    public const BIG5_CHINESE_NOPAD_CI = 'big5_chinese_nopad_ci';
    public const DEC8_SWEDISH_NOPAD_CI = 'dec8_swedish_nopad_ci';
    public const CP850_GENERAL_NOPAD_CI = 'cp850_general_nopad_ci';
    public const HP8_ENGLISH_NOPAD_CI = 'hp8_english_nopad_ci';
    public const KOI8R_GENERAL_NOPAD_CI = 'koi8r_general_nopad_ci';
    public const LATIN1_SWEDISH_NOPAD_CI = 'latin1_swedish_nopad_ci';
    public const LATIN2_GENERAL_NOPAD_CI = 'latin2_general_nopad_ci';
    public const SWE7_SWEDISH_NOPAD_CI = 'swe7_swedish_nopad_ci';
    public const ASCII_GENERAL_NOPAD_CI = 'ascii_general_nopad_ci';
    public const UJIS_JAPANESE_NOPAD_CI = 'ujis_japanese_nopad_ci';
    public const SJIS_JAPANESE_NOPAD_CI = 'sjis_japanese_nopad_ci';
    public const HEBREW_GENERAL_NOPAD_CI = 'hebrew_general_nopad_ci';
    public const TIS620_THAI_NOPAD_CI = 'tis620_thai_nopad_ci';
    public const EUCKR_KOREAN_NOPAD_CI = 'euckr_korean_nopad_ci';
    public const KOI8U_GENERAL_NOPAD_CI = 'koi8u_general_nopad_ci';
    public const GB2312_CHINESE_NOPAD_CI = 'gb2312_chinese_nopad_ci';
    public const GREEK_GENERAL_NOPAD_CI = 'greek_general_nopad_ci';
    public const CP1250_GENERAL_NOPAD_CI = 'cp1250_general_nopad_ci';
    public const GBK_CHINESE_NOPAD_CI = 'gbk_chinese_nopad_ci';
    public const LATIN5_TURKISH_NOPAD_CI = 'latin5_turkish_nopad_ci';
    public const ARMSCII8_GENERAL_NOPAD_CI = 'armscii8_general_nopad_ci';
    public const UTF8MB3_GENERAL_NOPAD_CI = 'utf8mb3_general_nopad_ci';
    public const UCS2_GENERAL_NOPAD_CI = 'ucs2_general_nopad_ci';
    public const CP866_GENERAL_NOPAD_CI = 'cp866_general_nopad_ci';
    public const KEYBCS2_GENERAL_NOPAD_CI = 'keybcs2_general_nopad_ci';
    public const MACCE_GENERAL_NOPAD_CI = 'macce_general_nopad_ci';
    public const MACROMAN_GENERAL_NOPAD_CI = 'macroman_general_nopad_ci';
    public const CP852_GENERAL_NOPAD_CI = 'cp852_general_nopad_ci';
    public const LATIN7_GENERAL_NOPAD_CI = 'latin7_general_nopad_ci';
    public const MACCE_NOPAD_BIN = 'macce_nopad_bin';
    public const UTF8MB4_GENERAL_NOPAD_CI = 'utf8mb4_general_nopad_ci';
    public const UTF8MB4_NOPAD_BIN = 'utf8mb4_nopad_bin';
    public const LATIN1_NOPAD_BIN = 'latin1_nopad_bin';
    public const CP1251_NOPAD_BIN = 'cp1251_nopad_bin';
    public const CP1251_GENERAL_NOPAD_CI = 'cp1251_general_nopad_ci';
    public const MACROMAN_NOPAD_BIN = 'macroman_nopad_bin';
    public const UTF16_GENERAL_NOPAD_CI = 'utf16_general_nopad_ci';
    public const UTF16_NOPAD_BIN = 'utf16_nopad_bin';
    public const UTF16LE_GENERAL_NOPAD_CI = 'utf16le_general_nopad_ci';
    public const CP1256_GENERAL_NOPAD_CI = 'cp1256_general_nopad_ci';
    public const CP1257_NOPAD_BIN = 'cp1257_nopad_bin';
    public const CP1257_GENERAL_NOPAD_CI = 'cp1257_general_nopad_ci';
    public const UTF32_GENERAL_NOPAD_CI = 'utf32_general_nopad_ci';
    public const UTF32_NOPAD_BIN = 'utf32_nopad_bin';
    public const UTF16LE_NOPAD_BIN = 'utf16le_nopad_bin';
    public const ARMSCII8_NOPAD_BIN = 'armscii8_nopad_bin';
    public const ASCII_NOPAD_BIN = 'ascii_nopad_bin';
    public const CP1250_NOPAD_BIN = 'cp1250_nopad_bin';
    public const CP1256_NOPAD_BIN = 'cp1256_nopad_bin';
    public const CP866_NOPAD_BIN = 'cp866_nopad_bin';
    public const DEC8_NOPAD_BIN = 'dec8_nopad_bin';
    public const GREEK_NOPAD_BIN = 'greek_nopad_bin';
    public const HEBREW_NOPAD_BIN = 'hebrew_nopad_bin';
    public const HP8_NOPAD_BIN = 'hp8_nopad_bin';
    public const KEYBCS2_NOPAD_BIN = 'keybcs2_nopad_bin';
    public const KOI8R_NOPAD_BIN = 'koi8r_nopad_bin';
    public const KOI8U_NOPAD_BIN = 'koi8u_nopad_bin';
    public const LATIN2_NOPAD_BIN = 'latin2_nopad_bin';
    public const LATIN5_NOPAD_BIN = 'latin5_nopad_bin';
    public const LATIN7_NOPAD_BIN = 'latin7_nopad_bin';
    public const CP850_NOPAD_BIN = 'cp850_nopad_bin';
    public const CP852_NOPAD_BIN = 'cp852_nopad_bin';
    public const SWE7_NOPAD_BIN = 'swe7_nopad_bin';
    public const UTF8MB3_NOPAD_BIN = 'utf8mb3_nopad_bin';
    public const BIG5_NOPAD_BIN = 'big5_nopad_bin';
    public const EUCKR_NOPAD_BIN = 'euckr_nopad_bin';
    public const GB2312_NOPAD_BIN = 'gb2312_nopad_bin';
    public const GBK_NOPAD_BIN = 'gbk_nopad_bin';
    public const SJIS_NOPAD_BIN = 'sjis_nopad_bin';
    public const TIS620_NOPAD_BIN = 'tis620_nopad_bin';
    public const UCS2_NOPAD_BIN = 'ucs2_nopad_bin';
    public const UJIS_NOPAD_BIN = 'ujis_nopad_bin';
    public const GEOSTD8_GENERAL_NOPAD_CI = 'geostd8_general_nopad_ci';
    public const GEOSTD8_NOPAD_BIN = 'geostd8_nopad_bin';
    public const CP932_JAPANESE_NOPAD_CI = 'cp932_japanese_nopad_ci';
    public const CP932_NOPAD_BIN = 'cp932_nopad_bin';
    public const EUCJPMS_JAPANESE_NOPAD_CI = 'eucjpms_japanese_nopad_ci';
    public const EUCJPMS_NOPAD_BIN = 'eucjpms_nopad_bin';
    public const UTF16_UNICODE_NOPAD_CI = 'utf16_unicode_nopad_ci';
    public const UTF16_UNICODE_520_NOPAD_CI = 'utf16_unicode_520_nopad_ci';
    public const UCS2_UNICODE_NOPAD_CI = 'ucs2_unicode_nopad_ci';
    public const UCS2_UNICODE_520_NOPAD_CI = 'ucs2_unicode_520_nopad_ci';
    public const UTF32_UNICODE_NOPAD_CI = 'utf32_unicode_nopad_ci';
    public const UTF32_UNICODE_520_NOPAD_CI = 'utf32_unicode_520_nopad_ci';
    public const UTF8MB3_UNICODE_NOPAD_CI = 'utf8mb3_unicode_nopad_ci';
    public const UTF8MB3_UNICODE_520_NOPAD_CI = 'utf8mb3_unicode_520_nopad_ci';
    public const UTF8MB4_UNICODE_NOPAD_CI = 'utf8mb4_unicode_nopad_ci';
    public const UTF8MB4_UNICODE_520_NOPAD_CI = 'utf8mb4_unicode_520_nopad_ci';

    public const BIG5 = 'big5';
    public const LATIN2 = 'latin2';
    public const DEC8 = 'dec8';
    public const CP850 = 'cp850';
    public const LATIN1 = 'latin1';
    public const HP8 = 'hp8';
    public const KOI8R = 'koi8r';
    public const SWE7 = 'swe7';
    public const ASCII = 'ascii';
    public const UJIS = 'ujis';
    public const SJIS = 'sjis';
    public const CP1251 = 'cp1251';
    public const HEBREW = 'hebrew';
    public const TIS620 = 'tis620';
    public const EUCKR = 'euckr';
    public const LATIN7 = 'latin7';
    public const KOI8U = 'koi8u';
    public const GB2312 = 'gb2312';
    public const GREEK = 'greek';
    public const CP1250 = 'cp1250';
    public const GBK = 'gbk';
    public const CP1257 = 'cp1257';
    public const LATIN5 = 'latin5';
    public const ARMSCII8 = 'armscii8';
    public const UTF8MB3 = 'utf8mb3';
    public const UCS2 = 'ucs2';
    public const CP866 = 'cp866';
    public const KEYBCS2 = 'keybcs2';
    public const MACCE = 'macce';
    public const MACROMAN = 'macroman';
    public const CP852 = 'cp852';
    public const UTF8MB4 = 'utf8mb4';
    public const UTF16 = 'utf16';
    public const UTF16LE = 'utf16le';
    public const CP1256 = 'cp1256';
    public const UTF32 = 'utf32';
    public const GEOSTD8 = 'geostd8';
    public const CP932 = 'cp932';
    public const EUCJPMS = 'eucjpms';

    public const COLLATIONS = [
        self::UCA1400_AI_CI => null,
        self::UCA1400_AI_CS => null,
        self::UCA1400_AS_CI => null,
        self::UCA1400_AS_CS => null,
        self::UCA1400_NOPAD_AI_CI => null,
        self::UCA1400_NOPAD_AI_CS => null,
        self::UCA1400_NOPAD_AS_CI => null,
        self::UCA1400_NOPAD_AS_CS => null,
        self::UCA1400_ICELANDIC_AI_CI => null,
        self::UCA1400_ICELANDIC_AI_CS => null,
        self::UCA1400_ICELANDIC_AS_CI => null,
        self::UCA1400_ICELANDIC_AS_CS => null,
        self::UCA1400_ICELANDIC_NOPAD_AI_CI => null,
        self::UCA1400_ICELANDIC_NOPAD_AI_CS => null,
        self::UCA1400_ICELANDIC_NOPAD_AS_CI => null,
        self::UCA1400_ICELANDIC_NOPAD_AS_CS => null,
        self::UCA1400_LATVIAN_AI_CI => null,
        self::UCA1400_LATVIAN_AI_CS => null,
        self::UCA1400_LATVIAN_AS_CI => null,
        self::UCA1400_LATVIAN_AS_CS => null,
        self::UCA1400_LATVIAN_NOPAD_AI_CI => null,
        self::UCA1400_LATVIAN_NOPAD_AI_CS => null,
        self::UCA1400_LATVIAN_NOPAD_AS_CI => null,
        self::UCA1400_LATVIAN_NOPAD_AS_CS => null,
        self::UCA1400_ROMANIAN_AI_CI => null,
        self::UCA1400_ROMANIAN_AI_CS => null,
        self::UCA1400_ROMANIAN_AS_CI => null,
        self::UCA1400_ROMANIAN_AS_CS => null,
        self::UCA1400_ROMANIAN_NOPAD_AI_CI => null,
        self::UCA1400_ROMANIAN_NOPAD_AI_CS => null,
        self::UCA1400_ROMANIAN_NOPAD_AS_CI => null,
        self::UCA1400_ROMANIAN_NOPAD_AS_CS => null,
        self::UCA1400_SLOVENIAN_AI_CI => null,
        self::UCA1400_SLOVENIAN_AI_CS => null,
        self::UCA1400_SLOVENIAN_AS_CI => null,
        self::UCA1400_SLOVENIAN_AS_CS => null,
        self::UCA1400_SLOVENIAN_NOPAD_AI_CI => null,
        self::UCA1400_SLOVENIAN_NOPAD_AI_CS => null,
        self::UCA1400_SLOVENIAN_NOPAD_AS_CI => null,
        self::UCA1400_SLOVENIAN_NOPAD_AS_CS => null,
        self::UCA1400_POLISH_AI_CI => null,
        self::UCA1400_POLISH_AI_CS => null,
        self::UCA1400_POLISH_AS_CI => null,
        self::UCA1400_POLISH_AS_CS => null,
        self::UCA1400_POLISH_NOPAD_AI_CI => null,
        self::UCA1400_POLISH_NOPAD_AI_CS => null,
        self::UCA1400_POLISH_NOPAD_AS_CI => null,
        self::UCA1400_POLISH_NOPAD_AS_CS => null,
        self::UCA1400_ESTONIAN_AI_CI => null,
        self::UCA1400_ESTONIAN_AI_CS => null,
        self::UCA1400_ESTONIAN_AS_CI => null,
        self::UCA1400_ESTONIAN_AS_CS => null,
        self::UCA1400_ESTONIAN_NOPAD_AI_CI => null,
        self::UCA1400_ESTONIAN_NOPAD_AI_CS => null,
        self::UCA1400_ESTONIAN_NOPAD_AS_CI => null,
        self::UCA1400_ESTONIAN_NOPAD_AS_CS => null,
        self::UCA1400_SPANISH_AI_CI => null,
        self::UCA1400_SPANISH_AI_CS => null,
        self::UCA1400_SPANISH_AS_CI => null,
        self::UCA1400_SPANISH_AS_CS => null,
        self::UCA1400_SPANISH_NOPAD_AI_CI => null,
        self::UCA1400_SPANISH_NOPAD_AI_CS => null,
        self::UCA1400_SPANISH_NOPAD_AS_CI => null,
        self::UCA1400_SPANISH_NOPAD_AS_CS => null,
        self::UCA1400_SWEDISH_AI_CI => null,
        self::UCA1400_SWEDISH_AI_CS => null,
        self::UCA1400_SWEDISH_AS_CI => null,
        self::UCA1400_SWEDISH_AS_CS => null,
        self::UCA1400_SWEDISH_NOPAD_AI_CI => null,
        self::UCA1400_SWEDISH_NOPAD_AI_CS => null,
        self::UCA1400_SWEDISH_NOPAD_AS_CI => null,
        self::UCA1400_SWEDISH_NOPAD_AS_CS => null,
        self::UCA1400_TURKISH_AI_CI => null,
        self::UCA1400_TURKISH_AI_CS => null,
        self::UCA1400_TURKISH_AS_CI => null,
        self::UCA1400_TURKISH_AS_CS => null,
        self::UCA1400_TURKISH_NOPAD_AI_CI => null,
        self::UCA1400_TURKISH_NOPAD_AI_CS => null,
        self::UCA1400_TURKISH_NOPAD_AS_CI => null,
        self::UCA1400_TURKISH_NOPAD_AS_CS => null,
        self::UCA1400_CZECH_AI_CI => null,
        self::UCA1400_CZECH_AI_CS => null,
        self::UCA1400_CZECH_AS_CI => null,
        self::UCA1400_CZECH_AS_CS => null,
        self::UCA1400_CZECH_NOPAD_AI_CI => null,
        self::UCA1400_CZECH_NOPAD_AI_CS => null,
        self::UCA1400_CZECH_NOPAD_AS_CI => null,
        self::UCA1400_CZECH_NOPAD_AS_CS => null,
        self::UCA1400_DANISH_AI_CI => null,
        self::UCA1400_DANISH_AI_CS => null,
        self::UCA1400_DANISH_AS_CI => null,
        self::UCA1400_DANISH_AS_CS => null,
        self::UCA1400_DANISH_NOPAD_AI_CI => null,
        self::UCA1400_DANISH_NOPAD_AI_CS => null,
        self::UCA1400_DANISH_NOPAD_AS_CI => null,
        self::UCA1400_DANISH_NOPAD_AS_CS => null,
        self::UCA1400_LITHUANIAN_AI_CI => null,
        self::UCA1400_LITHUANIAN_AI_CS => null,
        self::UCA1400_LITHUANIAN_AS_CI => null,
        self::UCA1400_LITHUANIAN_AS_CS => null,
        self::UCA1400_LITHUANIAN_NOPAD_AI_CI => null,
        self::UCA1400_LITHUANIAN_NOPAD_AI_CS => null,
        self::UCA1400_LITHUANIAN_NOPAD_AS_CI => null,
        self::UCA1400_LITHUANIAN_NOPAD_AS_CS => null,
        self::UCA1400_SLOVAK_AI_CI => null,
        self::UCA1400_SLOVAK_AI_CS => null,
        self::UCA1400_SLOVAK_AS_CI => null,
        self::UCA1400_SLOVAK_AS_CS => null,
        self::UCA1400_SLOVAK_NOPAD_AI_CI => null,
        self::UCA1400_SLOVAK_NOPAD_AI_CS => null,
        self::UCA1400_SLOVAK_NOPAD_AS_CI => null,
        self::UCA1400_SLOVAK_NOPAD_AS_CS => null,
        self::UCA1400_SPANISH2_AI_CI => null,
        self::UCA1400_SPANISH2_AI_CS => null,
        self::UCA1400_SPANISH2_AS_CI => null,
        self::UCA1400_SPANISH2_AS_CS => null,
        self::UCA1400_SPANISH2_NOPAD_AI_CI => null,
        self::UCA1400_SPANISH2_NOPAD_AI_CS => null,
        self::UCA1400_SPANISH2_NOPAD_AS_CI => null,
        self::UCA1400_SPANISH2_NOPAD_AS_CS => null,
        self::UCA1400_ROMAN_AI_CI => null,
        self::UCA1400_ROMAN_AI_CS => null,
        self::UCA1400_ROMAN_AS_CI => null,
        self::UCA1400_ROMAN_AS_CS => null,
        self::UCA1400_ROMAN_NOPAD_AI_CI => null,
        self::UCA1400_ROMAN_NOPAD_AI_CS => null,
        self::UCA1400_ROMAN_NOPAD_AS_CI => null,
        self::UCA1400_ROMAN_NOPAD_AS_CS => null,
        self::UCA1400_PERSIAN_AI_CI => null,
        self::UCA1400_PERSIAN_AI_CS => null,
        self::UCA1400_PERSIAN_AS_CI => null,
        self::UCA1400_PERSIAN_AS_CS => null,
        self::UCA1400_PERSIAN_NOPAD_AI_CI => null,
        self::UCA1400_PERSIAN_NOPAD_AI_CS => null,
        self::UCA1400_PERSIAN_NOPAD_AS_CI => null,
        self::UCA1400_PERSIAN_NOPAD_AS_CS => null,
        self::UCA1400_ESPERANTO_AI_CI => null,
        self::UCA1400_ESPERANTO_AI_CS => null,
        self::UCA1400_ESPERANTO_AS_CI => null,
        self::UCA1400_ESPERANTO_AS_CS => null,
        self::UCA1400_ESPERANTO_NOPAD_AI_CI => null,
        self::UCA1400_ESPERANTO_NOPAD_AI_CS => null,
        self::UCA1400_ESPERANTO_NOPAD_AS_CI => null,
        self::UCA1400_ESPERANTO_NOPAD_AS_CS => null,
        self::UCA1400_HUNGARIAN_AI_CI => null,
        self::UCA1400_HUNGARIAN_AI_CS => null,
        self::UCA1400_HUNGARIAN_AS_CI => null,
        self::UCA1400_HUNGARIAN_AS_CS => null,
        self::UCA1400_HUNGARIAN_NOPAD_AI_CI => null,
        self::UCA1400_HUNGARIAN_NOPAD_AI_CS => null,
        self::UCA1400_HUNGARIAN_NOPAD_AS_CI => null,
        self::UCA1400_HUNGARIAN_NOPAD_AS_CS => null,
        self::UCA1400_SINHALA_AI_CI => null,
        self::UCA1400_SINHALA_AI_CS => null,
        self::UCA1400_SINHALA_AS_CI => null,
        self::UCA1400_SINHALA_AS_CS => null,
        self::UCA1400_SINHALA_NOPAD_AI_CI => null,
        self::UCA1400_SINHALA_NOPAD_AI_CS => null,
        self::UCA1400_SINHALA_NOPAD_AS_CI => null,
        self::UCA1400_SINHALA_NOPAD_AS_CS => null,
        self::UCA1400_GERMAN2_AI_CI => null,
        self::UCA1400_GERMAN2_AI_CS => null,
        self::UCA1400_GERMAN2_AS_CI => null,
        self::UCA1400_GERMAN2_AS_CS => null,
        self::UCA1400_GERMAN2_NOPAD_AI_CI => null,
        self::UCA1400_GERMAN2_NOPAD_AI_CS => null,
        self::UCA1400_GERMAN2_NOPAD_AS_CI => null,
        self::UCA1400_GERMAN2_NOPAD_AS_CS => null,
        self::UCA1400_VIETNAMESE_AI_CI => null,
        self::UCA1400_VIETNAMESE_AI_CS => null,
        self::UCA1400_VIETNAMESE_AS_CI => null,
        self::UCA1400_VIETNAMESE_AS_CS => null,
        self::UCA1400_VIETNAMESE_NOPAD_AI_CI => null,
        self::UCA1400_VIETNAMESE_NOPAD_AI_CS => null,
        self::UCA1400_VIETNAMESE_NOPAD_AS_CI => null,
        self::UCA1400_VIETNAMESE_NOPAD_AS_CS => null,
        self::UCA1400_CROATIAN_AI_CI => null,
        self::UCA1400_CROATIAN_AI_CS => null,
        self::UCA1400_CROATIAN_AS_CI => null,
        self::UCA1400_CROATIAN_AS_CS => null,
        self::UCA1400_CROATIAN_NOPAD_AI_CI => null,
        self::UCA1400_CROATIAN_NOPAD_AI_CS => null,
        self::UCA1400_CROATIAN_NOPAD_AS_CI => null,
        self::UCA1400_CROATIAN_NOPAD_AS_CS => null,
        self::BIG5_CHINESE_CI => self::BIG5,
        self::LATIN2_CZECH_CS => self::LATIN2,
        self::DEC8_SWEDISH_CI => self::DEC8,
        self::CP850_GENERAL_CI => self::CP850,
        self::LATIN1_GERMAN1_CI => self::LATIN1,
        self::HP8_ENGLISH_CI => self::HP8,
        self::KOI8R_GENERAL_CI => self::KOI8R,
        self::LATIN1_SWEDISH_CI => self::LATIN1,
        self::LATIN2_GENERAL_CI => self::LATIN2,
        self::SWE7_SWEDISH_CI => self::SWE7,
        self::ASCII_GENERAL_CI => self::ASCII,
        self::UJIS_JAPANESE_CI => self::UJIS,
        self::SJIS_JAPANESE_CI => self::SJIS,
        self::CP1251_BULGARIAN_CI => self::CP1251,
        self::LATIN1_DANISH_CI => self::LATIN1,
        self::HEBREW_GENERAL_CI => self::HEBREW,
        self::TIS620_THAI_CI => self::TIS620,
        self::EUCKR_KOREAN_CI => self::EUCKR,
        self::LATIN7_ESTONIAN_CS => self::LATIN7,
        self::LATIN2_HUNGARIAN_CI => self::LATIN2,
        self::KOI8U_GENERAL_CI => self::KOI8U,
        self::CP1251_UKRAINIAN_CI => self::CP1251,
        self::GB2312_CHINESE_CI => self::GB2312,
        self::GREEK_GENERAL_CI => self::GREEK,
        self::CP1250_GENERAL_CI => self::CP1250,
        self::LATIN2_CROATIAN_CI => self::LATIN2,
        self::GBK_CHINESE_CI => self::GBK,
        self::CP1257_LITHUANIAN_CI => self::CP1257,
        self::LATIN5_TURKISH_CI => self::LATIN5,
        self::LATIN1_GERMAN2_CI => self::LATIN1,
        self::ARMSCII8_GENERAL_CI => self::ARMSCII8,
        self::UTF8MB3_GENERAL_CI => self::UTF8MB3,
        self::CP1250_CZECH_CS => self::CP1250,
        self::UCS2_GENERAL_CI => self::UCS2,
        self::CP866_GENERAL_CI => self::CP866,
        self::KEYBCS2_GENERAL_CI => self::KEYBCS2,
        self::MACCE_GENERAL_CI => self::MACCE,
        self::MACROMAN_GENERAL_CI => self::MACROMAN,
        self::CP852_GENERAL_CI => self::CP852,
        self::LATIN7_GENERAL_CI => self::LATIN7,
        self::LATIN7_GENERAL_CS => self::LATIN7,
        self::MACCE_BIN => self::MACCE,
        self::CP1250_CROATIAN_CI => self::CP1250,
        self::UTF8MB4_GENERAL_CI => self::UTF8MB4,
        self::UTF8MB4_BIN => self::UTF8MB4,
        self::LATIN1_BIN => self::LATIN1,
        self::LATIN1_GENERAL_CI => self::LATIN1,
        self::LATIN1_GENERAL_CS => self::LATIN1,
        self::CP1251_BIN => self::CP1251,
        self::CP1251_GENERAL_CI => self::CP1251,
        self::CP1251_GENERAL_CS => self::CP1251,
        self::MACROMAN_BIN => self::MACROMAN,
        self::UTF16_GENERAL_CI => self::UTF16,
        self::UTF16_BIN => self::UTF16,
        self::UTF16LE_GENERAL_CI => self::UTF16LE,
        self::CP1256_GENERAL_CI => self::CP1256,
        self::CP1257_BIN => self::CP1257,
        self::CP1257_GENERAL_CI => self::CP1257,
        self::UTF32_GENERAL_CI => self::UTF32,
        self::UTF32_BIN => self::UTF32,
        self::UTF16LE_BIN => self::UTF16LE,
        self::BINARY => self::BINARY,
        self::ARMSCII8_BIN => self::ARMSCII8,
        self::ASCII_BIN => self::ASCII,
        self::CP1250_BIN => self::CP1250,
        self::CP1256_BIN => self::CP1256,
        self::CP866_BIN => self::CP866,
        self::DEC8_BIN => self::DEC8,
        self::GREEK_BIN => self::GREEK,
        self::HEBREW_BIN => self::HEBREW,
        self::HP8_BIN => self::HP8,
        self::KEYBCS2_BIN => self::KEYBCS2,
        self::KOI8R_BIN => self::KOI8R,
        self::KOI8U_BIN => self::KOI8U,
        self::LATIN2_BIN => self::LATIN2,
        self::LATIN5_BIN => self::LATIN5,
        self::LATIN7_BIN => self::LATIN7,
        self::CP850_BIN => self::CP850,
        self::CP852_BIN => self::CP852,
        self::SWE7_BIN => self::SWE7,
        self::UTF8MB3_BIN => self::UTF8MB3,
        self::BIG5_BIN => self::BIG5,
        self::EUCKR_BIN => self::EUCKR,
        self::GB2312_BIN => self::GB2312,
        self::GBK_BIN => self::GBK,
        self::SJIS_BIN => self::SJIS,
        self::TIS620_BIN => self::TIS620,
        self::UCS2_BIN => self::UCS2,
        self::UJIS_BIN => self::UJIS,
        self::GEOSTD8_GENERAL_CI => self::GEOSTD8,
        self::GEOSTD8_BIN => self::GEOSTD8,
        self::LATIN1_SPANISH_CI => self::LATIN1,
        self::CP932_JAPANESE_CI => self::CP932,
        self::CP932_BIN => self::CP932,
        self::EUCJPMS_JAPANESE_CI => self::EUCJPMS,
        self::EUCJPMS_BIN => self::EUCJPMS,
        self::CP1250_POLISH_CI => self::CP1250,
        self::UTF16_UNICODE_CI => self::UTF16,
        self::UTF16_ICELANDIC_CI => self::UTF16,
        self::UTF16_LATVIAN_CI => self::UTF16,
        self::UTF16_ROMANIAN_CI => self::UTF16,
        self::UTF16_SLOVENIAN_CI => self::UTF16,
        self::UTF16_POLISH_CI => self::UTF16,
        self::UTF16_ESTONIAN_CI => self::UTF16,
        self::UTF16_SPANISH_CI => self::UTF16,
        self::UTF16_SWEDISH_CI => self::UTF16,
        self::UTF16_TURKISH_CI => self::UTF16,
        self::UTF16_CZECH_CI => self::UTF16,
        self::UTF16_DANISH_CI => self::UTF16,
        self::UTF16_LITHUANIAN_CI => self::UTF16,
        self::UTF16_SLOVAK_CI => self::UTF16,
        self::UTF16_SPANISH2_CI => self::UTF16,
        self::UTF16_ROMAN_CI => self::UTF16,
        self::UTF16_PERSIAN_CI => self::UTF16,
        self::UTF16_ESPERANTO_CI => self::UTF16,
        self::UTF16_HUNGARIAN_CI => self::UTF16,
        self::UTF16_SINHALA_CI => self::UTF16,
        self::UTF16_GERMAN2_CI => self::UTF16,
        self::UTF16_CROATIAN_MYSQL561_CI => self::UTF16,
        self::UTF16_UNICODE_520_CI => self::UTF16,
        self::UTF16_VIETNAMESE_CI => self::UTF16,
        self::UCS2_UNICODE_CI => self::UCS2,
        self::UCS2_ICELANDIC_CI => self::UCS2,
        self::UCS2_LATVIAN_CI => self::UCS2,
        self::UCS2_ROMANIAN_CI => self::UCS2,
        self::UCS2_SLOVENIAN_CI => self::UCS2,
        self::UCS2_POLISH_CI => self::UCS2,
        self::UCS2_ESTONIAN_CI => self::UCS2,
        self::UCS2_SPANISH_CI => self::UCS2,
        self::UCS2_SWEDISH_CI => self::UCS2,
        self::UCS2_TURKISH_CI => self::UCS2,
        self::UCS2_CZECH_CI => self::UCS2,
        self::UCS2_DANISH_CI => self::UCS2,
        self::UCS2_LITHUANIAN_CI => self::UCS2,
        self::UCS2_SLOVAK_CI => self::UCS2,
        self::UCS2_SPANISH2_CI => self::UCS2,
        self::UCS2_ROMAN_CI => self::UCS2,
        self::UCS2_PERSIAN_CI => self::UCS2,
        self::UCS2_ESPERANTO_CI => self::UCS2,
        self::UCS2_HUNGARIAN_CI => self::UCS2,
        self::UCS2_SINHALA_CI => self::UCS2,
        self::UCS2_GERMAN2_CI => self::UCS2,
        self::UCS2_CROATIAN_MYSQL561_CI => self::UCS2,
        self::UCS2_UNICODE_520_CI => self::UCS2,
        self::UCS2_VIETNAMESE_CI => self::UCS2,
        self::UCS2_GENERAL_MYSQL500_CI => self::UCS2,
        self::UTF32_UNICODE_CI => self::UTF32,
        self::UTF32_ICELANDIC_CI => self::UTF32,
        self::UTF32_LATVIAN_CI => self::UTF32,
        self::UTF32_ROMANIAN_CI => self::UTF32,
        self::UTF32_SLOVENIAN_CI => self::UTF32,
        self::UTF32_POLISH_CI => self::UTF32,
        self::UTF32_ESTONIAN_CI => self::UTF32,
        self::UTF32_SPANISH_CI => self::UTF32,
        self::UTF32_SWEDISH_CI => self::UTF32,
        self::UTF32_TURKISH_CI => self::UTF32,
        self::UTF32_CZECH_CI => self::UTF32,
        self::UTF32_DANISH_CI => self::UTF32,
        self::UTF32_LITHUANIAN_CI => self::UTF32,
        self::UTF32_SLOVAK_CI => self::UTF32,
        self::UTF32_SPANISH2_CI => self::UTF32,
        self::UTF32_ROMAN_CI => self::UTF32,
        self::UTF32_PERSIAN_CI => self::UTF32,
        self::UTF32_ESPERANTO_CI => self::UTF32,
        self::UTF32_HUNGARIAN_CI => self::UTF32,
        self::UTF32_SINHALA_CI => self::UTF32,
        self::UTF32_GERMAN2_CI => self::UTF32,
        self::UTF32_CROATIAN_MYSQL561_CI => self::UTF32,
        self::UTF32_UNICODE_520_CI => self::UTF32,
        self::UTF32_VIETNAMESE_CI => self::UTF32,
        self::UTF8MB3_UNICODE_CI => self::UTF8MB3,
        self::UTF8MB3_ICELANDIC_CI => self::UTF8MB3,
        self::UTF8MB3_LATVIAN_CI => self::UTF8MB3,
        self::UTF8MB3_ROMANIAN_CI => self::UTF8MB3,
        self::UTF8MB3_SLOVENIAN_CI => self::UTF8MB3,
        self::UTF8MB3_POLISH_CI => self::UTF8MB3,
        self::UTF8MB3_ESTONIAN_CI => self::UTF8MB3,
        self::UTF8MB3_SPANISH_CI => self::UTF8MB3,
        self::UTF8MB3_SWEDISH_CI => self::UTF8MB3,
        self::UTF8MB3_TURKISH_CI => self::UTF8MB3,
        self::UTF8MB3_CZECH_CI => self::UTF8MB3,
        self::UTF8MB3_DANISH_CI => self::UTF8MB3,
        self::UTF8MB3_LITHUANIAN_CI => self::UTF8MB3,
        self::UTF8MB3_SLOVAK_CI => self::UTF8MB3,
        self::UTF8MB3_SPANISH2_CI => self::UTF8MB3,
        self::UTF8MB3_ROMAN_CI => self::UTF8MB3,
        self::UTF8MB3_PERSIAN_CI => self::UTF8MB3,
        self::UTF8MB3_ESPERANTO_CI => self::UTF8MB3,
        self::UTF8MB3_HUNGARIAN_CI => self::UTF8MB3,
        self::UTF8MB3_SINHALA_CI => self::UTF8MB3,
        self::UTF8MB3_GERMAN2_CI => self::UTF8MB3,
        self::UTF8MB3_CROATIAN_MYSQL561_CI => self::UTF8MB3,
        self::UTF8MB3_UNICODE_520_CI => self::UTF8MB3,
        self::UTF8MB3_VIETNAMESE_CI => self::UTF8MB3,
        self::UTF8MB3_GENERAL_MYSQL500_CI => self::UTF8MB3,
        self::UTF8MB4_UNICODE_CI => self::UTF8MB4,
        self::UTF8MB4_ICELANDIC_CI => self::UTF8MB4,
        self::UTF8MB4_LATVIAN_CI => self::UTF8MB4,
        self::UTF8MB4_ROMANIAN_CI => self::UTF8MB4,
        self::UTF8MB4_SLOVENIAN_CI => self::UTF8MB4,
        self::UTF8MB4_POLISH_CI => self::UTF8MB4,
        self::UTF8MB4_ESTONIAN_CI => self::UTF8MB4,
        self::UTF8MB4_SPANISH_CI => self::UTF8MB4,
        self::UTF8MB4_SWEDISH_CI => self::UTF8MB4,
        self::UTF8MB4_TURKISH_CI => self::UTF8MB4,
        self::UTF8MB4_CZECH_CI => self::UTF8MB4,
        self::UTF8MB4_DANISH_CI => self::UTF8MB4,
        self::UTF8MB4_LITHUANIAN_CI => self::UTF8MB4,
        self::UTF8MB4_SLOVAK_CI => self::UTF8MB4,
        self::UTF8MB4_SPANISH2_CI => self::UTF8MB4,
        self::UTF8MB4_ROMAN_CI => self::UTF8MB4,
        self::UTF8MB4_PERSIAN_CI => self::UTF8MB4,
        self::UTF8MB4_ESPERANTO_CI => self::UTF8MB4,
        self::UTF8MB4_HUNGARIAN_CI => self::UTF8MB4,
        self::UTF8MB4_SINHALA_CI => self::UTF8MB4,
        self::UTF8MB4_GERMAN2_CI => self::UTF8MB4,
        self::UTF8MB4_CROATIAN_MYSQL561_CI => self::UTF8MB4,
        self::UTF8MB4_UNICODE_520_CI => self::UTF8MB4,
        self::UTF8MB4_VIETNAMESE_CI => self::UTF8MB4,
        self::UTF8MB3_CROATIAN_CI => self::UTF8MB3,
        self::UTF8MB3_MYANMAR_CI => self::UTF8MB3,
        self::UTF8MB3_THAI_520_W2 => self::UTF8MB3,
        self::UTF8MB4_CROATIAN_CI => self::UTF8MB4,
        self::UTF8MB4_MYANMAR_CI => self::UTF8MB4,
        self::UTF8MB4_THAI_520_W2 => self::UTF8MB4,
        self::UCS2_CROATIAN_CI => self::UCS2,
        self::UCS2_MYANMAR_CI => self::UCS2,
        self::UCS2_THAI_520_W2 => self::UCS2,
        self::UTF16_CROATIAN_CI => self::UTF16,
        self::UTF16_MYANMAR_CI => self::UTF16,
        self::UTF16_THAI_520_W2 => self::UTF16,
        self::UTF32_CROATIAN_CI => self::UTF32,
        self::UTF32_MYANMAR_CI => self::UTF32,
        self::UTF32_THAI_520_W2 => self::UTF32,
        self::BIG5_CHINESE_NOPAD_CI => self::BIG5,
        self::DEC8_SWEDISH_NOPAD_CI => self::DEC8,
        self::CP850_GENERAL_NOPAD_CI => self::CP850,
        self::HP8_ENGLISH_NOPAD_CI => self::HP8,
        self::KOI8R_GENERAL_NOPAD_CI => self::KOI8R,
        self::LATIN1_SWEDISH_NOPAD_CI => self::LATIN1,
        self::LATIN2_GENERAL_NOPAD_CI => self::LATIN2,
        self::SWE7_SWEDISH_NOPAD_CI => self::SWE7,
        self::ASCII_GENERAL_NOPAD_CI => self::ASCII,
        self::UJIS_JAPANESE_NOPAD_CI => self::UJIS,
        self::SJIS_JAPANESE_NOPAD_CI => self::SJIS,
        self::HEBREW_GENERAL_NOPAD_CI => self::HEBREW,
        self::TIS620_THAI_NOPAD_CI => self::TIS620,
        self::EUCKR_KOREAN_NOPAD_CI => self::EUCKR,
        self::KOI8U_GENERAL_NOPAD_CI => self::KOI8U,
        self::GB2312_CHINESE_NOPAD_CI => self::GB2312,
        self::GREEK_GENERAL_NOPAD_CI => self::GREEK,
        self::CP1250_GENERAL_NOPAD_CI => self::CP1250,
        self::GBK_CHINESE_NOPAD_CI => self::GBK,
        self::LATIN5_TURKISH_NOPAD_CI => self::LATIN5,
        self::ARMSCII8_GENERAL_NOPAD_CI => self::ARMSCII8,
        self::UTF8MB3_GENERAL_NOPAD_CI => self::UTF8MB3,
        self::UCS2_GENERAL_NOPAD_CI => self::UCS2,
        self::CP866_GENERAL_NOPAD_CI => self::CP866,
        self::KEYBCS2_GENERAL_NOPAD_CI => self::KEYBCS2,
        self::MACCE_GENERAL_NOPAD_CI => self::MACCE,
        self::MACROMAN_GENERAL_NOPAD_CI => self::MACROMAN,
        self::CP852_GENERAL_NOPAD_CI => self::CP852,
        self::LATIN7_GENERAL_NOPAD_CI => self::LATIN7,
        self::MACCE_NOPAD_BIN => self::MACCE,
        self::UTF8MB4_GENERAL_NOPAD_CI => self::UTF8MB4,
        self::UTF8MB4_NOPAD_BIN => self::UTF8MB4,
        self::LATIN1_NOPAD_BIN => self::LATIN1,
        self::CP1251_NOPAD_BIN => self::CP1251,
        self::CP1251_GENERAL_NOPAD_CI => self::CP1251,
        self::MACROMAN_NOPAD_BIN => self::MACROMAN,
        self::UTF16_GENERAL_NOPAD_CI => self::UTF16,
        self::UTF16_NOPAD_BIN => self::UTF16,
        self::UTF16LE_GENERAL_NOPAD_CI => self::UTF16LE,
        self::CP1256_GENERAL_NOPAD_CI => self::CP1256,
        self::CP1257_NOPAD_BIN => self::CP1257,
        self::CP1257_GENERAL_NOPAD_CI => self::CP1257,
        self::UTF32_GENERAL_NOPAD_CI => self::UTF32,
        self::UTF32_NOPAD_BIN => self::UTF32,
        self::UTF16LE_NOPAD_BIN => self::UTF16LE,
        self::ARMSCII8_NOPAD_BIN => self::ARMSCII8,
        self::ASCII_NOPAD_BIN => self::ASCII,
        self::CP1250_NOPAD_BIN => self::CP1250,
        self::CP1256_NOPAD_BIN => self::CP1256,
        self::CP866_NOPAD_BIN => self::CP866,
        self::DEC8_NOPAD_BIN => self::DEC8,
        self::GREEK_NOPAD_BIN => self::GREEK,
        self::HEBREW_NOPAD_BIN => self::HEBREW,
        self::HP8_NOPAD_BIN => self::HP8,
        self::KEYBCS2_NOPAD_BIN => self::KEYBCS2,
        self::KOI8R_NOPAD_BIN => self::KOI8R,
        self::KOI8U_NOPAD_BIN => self::KOI8U,
        self::LATIN2_NOPAD_BIN => self::LATIN2,
        self::LATIN5_NOPAD_BIN => self::LATIN5,
        self::LATIN7_NOPAD_BIN => self::LATIN7,
        self::CP850_NOPAD_BIN => self::CP850,
        self::CP852_NOPAD_BIN => self::CP852,
        self::SWE7_NOPAD_BIN => self::SWE7,
        self::UTF8MB3_NOPAD_BIN => self::UTF8MB3,
        self::BIG5_NOPAD_BIN => self::BIG5,
        self::EUCKR_NOPAD_BIN => self::EUCKR,
        self::GB2312_NOPAD_BIN => self::GB2312,
        self::GBK_NOPAD_BIN => self::GBK,
        self::SJIS_NOPAD_BIN => self::SJIS,
        self::TIS620_NOPAD_BIN => self::TIS620,
        self::UCS2_NOPAD_BIN => self::UCS2,
        self::UJIS_NOPAD_BIN => self::UJIS,
        self::GEOSTD8_GENERAL_NOPAD_CI => self::GEOSTD8,
        self::GEOSTD8_NOPAD_BIN => self::GEOSTD8,
        self::CP932_JAPANESE_NOPAD_CI => self::CP932,
        self::CP932_NOPAD_BIN => self::CP932,
        self::EUCJPMS_JAPANESE_NOPAD_CI => self::EUCJPMS,
        self::EUCJPMS_NOPAD_BIN => self::EUCJPMS,
        self::UTF16_UNICODE_NOPAD_CI => self::UTF16,
        self::UTF16_UNICODE_520_NOPAD_CI => self::UTF16,
        self::UCS2_UNICODE_NOPAD_CI => self::UCS2,
        self::UCS2_UNICODE_520_NOPAD_CI => self::UCS2,
        self::UTF32_UNICODE_NOPAD_CI => self::UTF32,
        self::UTF32_UNICODE_520_NOPAD_CI => self::UTF32,
        self::UTF8MB3_UNICODE_NOPAD_CI => self::UTF8MB3,
        self::UTF8MB3_UNICODE_520_NOPAD_CI => self::UTF8MB3,
        self::UTF8MB4_UNICODE_NOPAD_CI => self::UTF8MB4,
        self::UTF8MB4_UNICODE_520_NOPAD_CI => self::UTF8MB4,
    ];
    public const COLLATION_CHARSET = [
        self::BIG5 => self::BIG5_CHINESE_CI,
        self::LATIN2 => self::LATIN2_GENERAL_CI,
        self::DEC8 => self::DEC8_SWEDISH_CI,
        self::CP850 => self::CP850,
        self::LATIN1 => self::LATIN1_GENERAL_CI,
        self::HP8 => self::HP8_ENGLISH_CI,
        self::KOI8R => self::KOI8R_GENERAL_CI,
        self::SWE7 => self::SWE7_SWEDISH_CI,
        self::ASCII => self::ASCII_GENERAL_CI,
        self::UJIS => self::UJIS_JAPANESE_CI,
        self::SJIS => self::SJIS_JAPANESE_CI,
        self::CP1251 => self::CP1251_GENERAL_CI,
        self::HEBREW => self::HEBREW_GENERAL_CI,
        self::TIS620 => self::TIS620_THAI_CI,
        self::EUCKR => self::EUCKR_KOREAN_CI,
        self::LATIN7 => self::LATIN7_GENERAL_CI,
        self::KOI8U => self::KOI8U_GENERAL_CI,
        self::GB2312 => self::GB2312_CHINESE_CI,
        self::GREEK => self::GREEK_GENERAL_CI,
        self::CP1250 => self::CP1250_GENERAL_CI,
        self::GBK => self::GBK_CHINESE_CI,
        self::CP1257 => self::CP1257_GENERAL_CI,
        self::LATIN5 => self::LATIN5_TURKISH_CI,
        self::ARMSCII8 => self::ARMSCII8_GENERAL_CI,
        self::UTF8MB3 => self::UTF8MB3_GENERAL_CI,
        self::UCS2 => self::UCS2_GENERAL_CI,
        self::CP866 => self::CP866_GENERAL_CI,
        self::KEYBCS2 => self::KEYBCS2_GENERAL_CI,
        self::MACCE => self::MACCE_GENERAL_CI,
        self::MACROMAN => self::MACROMAN_GENERAL_CI,
        self::CP852 => self::CP852_GENERAL_CI,
        self::UTF8MB4 => self::UTF8MB4_GENERAL_CI,
        self::UTF16 => self::UTF16_GENERAL_CI,
        self::UTF16LE => self::UTF16LE_GENERAL_CI,
        self::CP1256 => self::CP1256_GENERAL_CI,
        self::UTF32 => self::UTF32_GENERAL_CI,
        // binary
        'bin' => self::BINARY,
        self::GEOSTD8 => self::GEOSTD8_GENERAL_CI,
        self::CP932 => self::CP932_JAPANESE_CI,
        self::EUCJPMS => self::EUCJPMS_JAPANESE_CI,
    ];

    /**
     * @param string $charset
     * @return string|null
     */
    public static function normalizeCharset(string $charset) : ?string
    {
        $charset = strtolower(trim($charset));

        return isset(self::COLLATION_CHARSET[$charset])
            ? $charset
            : null;
    }

    /**
     * Normalize collation
     * If collation or charset does not exist return null
     *
     * @param string $collation
     * @return ?string
     */
    public static function normalizeCollation(string $collation) : ?string
    {
        $collation = strtolower(trim($collation));
        // especial for bin
        $collation = str_replace('-', '_', $collation);
        if (isset(self::COLLATIONS[$collation])) {
            return $collation;
        }
        return self::COLLATION_CHARSET[$collation]??null;
    }
}
